
export enum Permissions {
  SEARCH_RESOURCES = "SEARCH_RESOURCES",
  VIEW_RESOURCES = "VIEW_RESOURCES",
  UPLOAD_THESIS = "UPLOAD_THESIS",
  VIEW_SUBMITTED_THESIS = "VIEW_SUBMITTED_THESIS",
  MODIFY_THESIS = "MODIFY_THESIS",
  MANAGE_SUBMITTED_THESES = "MANAGE_SUBMITTED_THESES",
  DELETE_THESIS = "DELETE_THESIS",
  VIEW_USER_AUDIT_LOG = "VIEW_USER_AUDIT_LOG",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  MANAGE_PERMISSION = "MANAGE_PERMISSION",
}

export enum Roles {
  GUEST = "GUEST",
  STUDENT = "STUDENT",
  LIBRARIAN = "LIBRARIAN",
  ADMIN = "ADMIN",
}
