import { TRPCProvider } from "@/shared/infrastructure/trpc/api/client";
import type { Metadata } from "next";
import { Inter as Font } from "next/font/google";
import "./globals.css";

const font = Font({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`font-sans ${font.variable} antialiased scroll-smooth`}>
				<TRPCProvider>{children}</TRPCProvider>
			</body>
		</html>
	);
}
